import React, { useState, useEffect, useMemo } from 'react';
import { supabase } from '../../lib/supabase';
import { invalidatePortfolioCache } from '../../hooks/usePortfolioData';
import { DEFAULT_PORTFOLIO_DATA } from '../../data/defaultPortfolioData';
import { BlogPost } from '../../types';
import Markdown from 'react-markdown';
import { 
  Plus, 
  Trash2, 
  Edit3, 
  Eye, 
  EyeOff, 
  Check, 
  Copy, 
  X, 
  FileText, 
  Globe, 
  Calendar, 
  Clock, 
  Search, 
  ExternalLink,
  Code,
  Download
} from 'lucide-react';

const SQL_SCHEMA = `-- 5. Blog Posts Table (Text-only, SEO-optimized Articles)
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    excerpt TEXT,
    content TEXT NOT NULL,
    keywords TEXT[],
    published BOOLEAN DEFAULT true,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    read_time_minutes INTEGER DEFAULT 5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for blog_posts
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- Public read access only where published = true
CREATE POLICY "Anyone can view published blog posts" ON public.blog_posts 
    FOR SELECT USING (published = true);

-- Full read/write access for admin
CREATE POLICY "Admins have full access to blog posts" ON public.blog_posts 
    FOR ALL USING (auth.role() = 'authenticated');`;

export function BlogAdmin() {
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [loading, setLoading] = useState(true);
  const [dbError, setDbError] = useState<string | null>(null);
  const [copiedSql, setCopiedSql] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  // Editing / Creating State
  const [isEditing, setIsEditing] = useState(false);
  const [activeTab, setActiveTab] = useState<'write' | 'preview'>('write');
  const [editingId, setEditingId] = useState<string | null>(null);
  
  // Form fields
  const [title, setTitle] = useState('');
  const [slug, setSlug] = useState('');
  const [excerpt, setExcerpt] = useState('');
  const [content, setContent] = useState('');
  const [keywords, setKeywords] = useState<string[]>([]);
  const [keywordInput, setKeywordInput] = useState('');
  const [published, setPublished] = useState(true);
  const [publishedAt, setPublishedAt] = useState('');
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);
  const [saveStatus, setSaveStatus] = useState<string | null>(null);

  // Helper to generate slug from title
  const generateSlug = (text: string) => {
    return text
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, '')
      .replace(/[\s_-]+/g, '-')
      .replace(/^-+|-+$/g, '');
  };

  const fetchPosts = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('blog_posts')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        console.warn('Supabase fetch error for blog_posts:', error.message);
        setDbError(error.message);
        // Fallback to local default data
        const fallback = (DEFAULT_PORTFOLIO_DATA.blog_posts as BlogPost[]) || [];
        setPosts(fallback);
      } else if (data) {
        setDbError(null);
        setPosts(data as BlogPost[]);
      }
    } catch (err: any) {
      console.warn('Catch error fetching blog_posts:', err);
      setDbError(err.message || 'Database error');
      const fallback = (DEFAULT_PORTFOLIO_DATA.blog_posts as BlogPost[]) || [];
      setPosts(fallback);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  const handleTitleChange = (newTitle: string) => {
    setTitle(newTitle);
    if (slugAutoGenerated) {
      setSlug(generateSlug(newTitle));
    }
  };

  const handleAddKeyword = (tag: string) => {
    const clean = tag.replace(/^#/, '').trim().toLowerCase();
    if (clean && !keywords.includes(clean)) {
      setKeywords([...keywords, clean]);
    }
    setKeywordInput('');
  };

  const handleRemoveKeyword = (index: number) => {
    setKeywords(keywords.filter((_, i) => i !== index));
  };

  const handleKeywordKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      handleAddKeyword(keywordInput);
    }
  };

  const openCreateModal = () => {
    setEditingId(null);
    setTitle('');
    setSlug('');
    setExcerpt('');
    setContent('');
    setKeywords([]);
    setKeywordInput('');
    setPublished(true);
    setPublishedAt(new Date().toISOString().slice(0, 16));
    setSlugAutoGenerated(true);
    setActiveTab('write');
    setIsEditing(true);
    setSaveStatus(null);
  };

  const openEditModal = (post: BlogPost) => {
    setEditingId(post.id);
    setTitle(post.title);
    setSlug(post.slug);
    setExcerpt(post.excerpt || '');
    setContent(post.content || '');
    setKeywords(post.keywords || []);
    setKeywordInput('');
    setPublished(post.published ?? true);
    setPublishedAt(post.published_at ? new Date(post.published_at).toISOString().slice(0, 16) : new Date().toISOString().slice(0, 16));
    setSlugAutoGenerated(false);
    setActiveTab('write');
    setIsEditing(true);
    setSaveStatus(null);
  };

  const wordCount = useMemo(() => {
    return content.split(/\s+/).filter(Boolean).length;
  }, [content]);

  const estimatedReadTime = useMemo(() => {
    return Math.max(1, Math.ceil(wordCount / 200));
  }, [wordCount]);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim() || !slug.trim() || !content.trim()) {
      alert('Title, Slug, and Content are required.');
      return;
    }

    setSaveStatus('saving');

    const cleanSlug = generateSlug(slug);
    const postPayload = {
      title: title.trim(),
      slug: cleanSlug,
      excerpt: excerpt.trim(),
      content: content.trim(),
      keywords: keywords,
      published: published,
      published_at: publishedAt ? new Date(publishedAt).toISOString() : new Date().toISOString(),
      read_time_minutes: estimatedReadTime
    };

    try {
      if (editingId) {
        // Update
        const { error } = await supabase
          .from('blog_posts')
          .update(postPayload)
          .eq('id', editingId);

        if (error) throw error;
      } else {
        // Create
        const { error } = await supabase
          .from('blog_posts')
          .insert([postPayload]);

        if (error) throw error;
      }

      invalidatePortfolioCache('blog_posts');
      await fetchPosts();
      setIsEditing(false);
      setSaveStatus(null);
    } catch (err: any) {
      console.error('Error saving blog post:', err);
      // If table doesn't exist yet, update local state for preview
      if (editingId) {
        setPosts(prev => prev.map(p => p.id === editingId ? { ...p, ...postPayload, id: editingId, created_at: p.created_at } : p));
      } else {
        const mockNew: BlogPost = {
          id: `local-${Date.now()}`,
          ...postPayload,
          created_at: new Date().toISOString()
        };
        setPosts(prev => [mockNew, ...prev]);
      }
      invalidatePortfolioCache('blog_posts');
      alert(`Note: Supabase table 'blog_posts' may not exist yet or failed to write (${err.message || err}). Changes updated locally.`);
      setIsEditing(false);
      setSaveStatus(null);
    }
  };

  const handleDelete = async (id: string, postTitle: string) => {
    if (!window.confirm(`Are you sure you want to delete "${postTitle}"?`)) {
      return;
    }

    try {
      const { error } = await supabase
        .from('blog_posts')
        .delete()
        .eq('id', id);

      if (error) throw error;

      invalidatePortfolioCache('blog_posts');
      await fetchPosts();
    } catch (err: any) {
      console.warn('Error deleting post:', err);
      setPosts(prev => prev.filter(p => p.id !== id));
      invalidatePortfolioCache('blog_posts');
    }
  };

  const handleTogglePublished = async (post: BlogPost) => {
    const newStatus = !post.published;
    try {
      const { error } = await supabase
        .from('blog_posts')
        .update({ published: newStatus })
        .eq('id', post.id);

      if (error) throw error;

      invalidatePortfolioCache('blog_posts');
      await fetchPosts();
    } catch (err) {
      // Fallback local update
      setPosts(prev => prev.map(p => p.id === post.id ? { ...p, published: newStatus } : p));
      invalidatePortfolioCache('blog_posts');
    }
  };

  const handleCopySql = () => {
    navigator.clipboard.writeText(SQL_SCHEMA);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 3000);
  };

  // Export sitemap XML with current posts
  const handleExportSitemap = () => {
    const domain = window.location.origin;
    const now = new Date().toISOString().slice(0, 10);
    
    let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;
    
    // Core routes
    xml += `  <url>\n    <loc>${domain}/</loc>\n    <lastmod>${now}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>1.0</priority>\n  </url>\n`;
    xml += `  <url>\n    <loc>${domain}/blog</loc>\n    <lastmod>${now}</lastmod>\n    <changefreq>daily</changefreq>\n    <priority>0.9</priority>\n  </url>\n`;
    xml += `  <url>\n    <loc>${domain}/contact</loc>\n    <lastmod>${now}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.8</priority>\n  </url>\n`;
    
    // Published blog posts
    posts.filter(p => p.published !== false).forEach(p => {
      const postDate = (p.published_at || p.created_at || now).slice(0, 10);
      xml += `  <url>\n    <loc>${domain}/blog/${p.slug}</loc>\n    <lastmod>${postDate}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.8</priority>\n  </url>\n`;
    });
    
    xml += `</urlset>\n`;

    const blob = new Blob([xml], { type: 'application/xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'sitemap.xml';
    a.click();
    URL.revokeObjectURL(url);
  };

  // Filtered posts
  const displayedPosts = useMemo(() => {
    if (!searchQuery.trim()) return posts;
    const q = searchQuery.toLowerCase();
    return posts.filter(p => 
      p.title.toLowerCase().includes(q) ||
      p.slug.toLowerCase().includes(q) ||
      p.keywords?.some(k => k.toLowerCase().includes(q))
    );
  }, [posts, searchQuery]);

  return (
    <div className="space-y-6">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-gray-200 pb-5">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-bold text-gray-900">Blog Posts Manager</h2>
            <span className="px-2 py-0.5 rounded-full text-xs font-semibold bg-emerald-100 text-emerald-800">
              Text-Only &amp; SEO
            </span>
          </div>
          <p className="text-sm text-gray-500 mt-1">
            Create, edit, and organize pure-text technical articles with instant Markdown preview, tags, and dynamic metadata.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleExportSitemap}
            className="inline-flex items-center gap-1.5 px-3 py-2 border border-gray-300 rounded-md text-xs font-medium text-gray-700 bg-white hover:bg-gray-50 transition-colors cursor-pointer"
            title="Download updated sitemap.xml containing all published posts"
          >
            <Download className="w-4 h-4 text-gray-500" />
            <span>Export Sitemap</span>
          </button>

          <button
            type="button"
            onClick={openCreateModal}
            className="inline-flex items-center gap-1.5 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-md text-sm font-medium transition-colors shadow-sm cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>New Article</span>
          </button>
        </div>
      </div>

      {/* Supabase Schema Notice if table doesn't exist */}
      {dbError && (
        <div className="rounded-lg bg-amber-50 border border-amber-200 p-4 text-sm text-amber-900 space-y-2">
          <div className="flex items-start justify-between">
            <div className="flex items-center gap-2 font-semibold text-amber-800">
              <Code className="w-4 h-4" />
              <span>Supabase Table Notice: `blog_posts` table setup</span>
            </div>
            <button
              type="button"
              onClick={handleCopySql}
              className="inline-flex items-center gap-1 px-2.5 py-1 text-xs rounded border border-amber-300 bg-white hover:bg-amber-100 transition-colors font-medium cursor-pointer"
            >
              {copiedSql ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedSql ? 'Copied SQL!' : 'Copy Setup SQL'}</span>
            </button>
          </div>
          <p className="text-xs text-amber-700">
            If you haven't created the <code className="bg-amber-100 px-1 py-0.5 rounded font-mono">blog_posts</code> table in your Supabase project yet, click <strong>"Copy Setup SQL"</strong> above and run it in the Supabase SQL Editor. In the meantime, local preview data is active!
          </p>
        </div>
      )}

      {/* Search & Filter Bar */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
        <div className="relative flex-1 max-w-sm">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search posts by title or keyword..."
            className="w-full pl-9 pr-3 py-1.5 text-sm border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
          />
        </div>
        <div className="text-xs text-gray-500">
          Total: {posts.length} {posts.length === 1 ? 'article' : 'articles'} ({posts.filter(p => p.published !== false).length} published)
        </div>
      </div>

      {/* Posts Table / List */}
      <div className="border border-gray-200 rounded-lg overflow-hidden bg-white shadow-sm">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th scope="col" className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                Article
              </th>
              <th scope="col" className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                Status
              </th>
              <th scope="col" className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider hidden md:table-cell">
                Keywords
              </th>
              <th scope="col" className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider hidden sm:table-cell">
                Date &amp; Read
              </th>
              <th scope="col" className="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase tracking-wider">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {displayedPosts.map((post) => {
              const isPub = post.published !== false;
              const formattedDate = new Date(post.published_at || post.created_at).toLocaleDateString('en-US', {
                month: 'short',
                day: 'numeric',
                year: 'numeric'
              });
              const readTime = post.read_time_minutes || Math.max(1, Math.ceil((post.content || '').split(/\s+/).filter(Boolean).length / 200));

              return (
                <tr key={post.id || post.slug} className="hover:bg-gray-50 transition-colors">
                  <td className="px-4 py-3.5">
                    <div className="space-y-1">
                      <div className="font-semibold text-gray-900 text-sm flex items-center gap-2">
                        <span>{post.title}</span>
                      </div>
                      <div className="flex items-center gap-2 text-xs text-gray-500 font-mono">
                        <span>/{post.slug}</span>
                        <a
                          href={`/blog/${post.slug}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-indigo-600 hover:text-indigo-800"
                          title="View live post"
                        >
                          <ExternalLink className="w-3.5 h-3.5" />
                        </a>
                      </div>
                    </div>
                  </td>

                  <td className="px-4 py-3.5 whitespace-nowrap">
                    <button
                      type="button"
                      onClick={() => handleTogglePublished(post)}
                      className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium cursor-pointer transition-colors ${
                        isPub 
                          ? 'bg-emerald-100 text-emerald-800 hover:bg-emerald-200' 
                          : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                      }`}
                      title="Click to toggle publish status"
                    >
                      {isPub ? <Eye className="w-3 h-3" /> : <EyeOff className="w-3 h-3" />}
                      <span>{isPub ? 'Published' : 'Draft'}</span>
                    </button>
                  </td>

                  <td className="px-4 py-3.5 hidden md:table-cell">
                    <div className="flex flex-wrap gap-1 max-w-xs">
                      {(post.keywords || []).slice(0, 3).map((kw, i) => (
                        <span key={i} className="px-2 py-0.5 rounded text-[11px] bg-gray-100 text-gray-600">
                          #{kw.replace(/^#/, '')}
                        </span>
                      ))}
                      {(post.keywords || []).length > 3 && (
                        <span className="text-[10px] text-gray-400 self-center">
                          +{post.keywords.length - 3}
                        </span>
                      )}
                    </div>
                  </td>

                  <td className="px-4 py-3.5 whitespace-nowrap text-xs text-gray-500 hidden sm:table-cell">
                    <div>{formattedDate}</div>
                    <div className="text-[11px] text-gray-400">{readTime} min read</div>
                  </td>

                  <td className="px-4 py-3.5 whitespace-nowrap text-right text-sm">
                    <div className="flex items-center justify-end gap-1">
                      <button
                        type="button"
                        onClick={() => openEditModal(post)}
                        className="p-1.5 text-indigo-600 hover:bg-indigo-50 rounded transition-colors cursor-pointer"
                        title="Edit post"
                      >
                        <Edit3 className="w-4 h-4" />
                      </button>
                      <button
                        type="button"
                        onClick={() => handleDelete(post.id, post.title)}
                        className="p-1.5 text-red-600 hover:bg-red-50 rounded transition-colors cursor-pointer"
                        title="Delete post"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}

            {displayedPosts.length === 0 && (
              <tr>
                <td colSpan={5} className="px-4 py-8 text-center text-gray-400 text-sm">
                  No articles found. Click <strong>"New Article"</strong> to compose your first blog post.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Editor Modal */}
      {isEditing && (
        <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4 overflow-y-auto">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-4xl max-h-[92vh] flex flex-col overflow-hidden text-gray-900">
            {/* Modal Header */}
            <div className="px-6 py-4 border-b border-gray-200 flex items-center justify-between bg-gray-50">
              <div>
                <h3 className="text-lg font-bold text-gray-900">
                  {editingId ? 'Edit Blog Post' : 'Compose New Article'}
                </h3>
                <p className="text-xs text-gray-500">
                  Pure text content with Markdown formatting, custom SEO tags, and auto-generated slug.
                </p>
              </div>
              <button
                type="button"
                onClick={() => setIsEditing(false)}
                className="text-gray-400 hover:text-gray-600 p-1 rounded-md"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Form */}
            <form onSubmit={handleSave} className="flex-1 overflow-y-auto p-6 space-y-5">
              {/* Title & Slug */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-semibold text-gray-700 uppercase tracking-wider mb-1">
                    Post Title *
                  </label>
                  <input
                    type="text"
                    required
                    value={title}
                    onChange={(e) => handleTitleChange(e.target.value)}
                    placeholder="e.g. Modern Web Animation Architecture"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm font-medium focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
                  />
                </div>

                <div>
                  <div className="flex items-center justify-between mb-1">
                    <label className="block text-xs font-semibold text-gray-700 uppercase tracking-wider">
                      URL Slug *
                    </label>
                    <span className="text-[11px] text-gray-400">
                      Auto-sanitized lowercase
                    </span>
                  </div>
                  <div className="flex items-center">
                    <span className="bg-gray-100 border border-r-0 border-gray-300 px-2.5 py-2 text-xs text-gray-500 rounded-l-md font-mono">
                      /blog/
                    </span>
                    <input
                      type="text"
                      required
                      value={slug}
                      onChange={(e) => {
                        setSlug(e.target.value);
                        setSlugAutoGenerated(false);
                      }}
                      placeholder="post-url-slug"
                      className="w-full px-3 py-2 border border-gray-300 rounded-r-md text-sm font-mono focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
                    />
                  </div>
                </div>
              </div>

              {/* Excerpt */}
              <div>
                <div className="flex items-center justify-between mb-1">
                  <label className="block text-xs font-semibold text-gray-700 uppercase tracking-wider">
                    Excerpt / SEO Description
                  </label>
                  <span className="text-[11px] text-gray-400">
                    {excerpt.length} characters (Recommended 140-160)
                  </span>
                </div>
                <textarea
                  rows={2}
                  value={excerpt}
                  onChange={(e) => setExcerpt(e.target.value)}
                  placeholder="Short summary displayed on the card and used as meta description..."
                  className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
                />
              </div>

              {/* Keywords Tag Input */}
              <div>
                <label className="block text-xs font-semibold text-gray-700 uppercase tracking-wider mb-1">
                  SEO Keywords / Hashtags
                </label>
                <div className="flex flex-wrap items-center gap-1.5 p-2 border border-gray-300 rounded-md bg-white">
                  {keywords.map((kw, i) => (
                    <span
                      key={i}
                      className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-indigo-50 text-indigo-700 text-xs font-medium border border-indigo-200"
                    >
                      #{kw}
                      <button
                        type="button"
                        onClick={() => handleRemoveKeyword(i)}
                        className="hover:text-indigo-900"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </span>
                  ))}
                  <input
                    type="text"
                    value={keywordInput}
                    onChange={(e) => setKeywordInput(e.target.value)}
                    onKeyDown={handleKeywordKeyDown}
                    placeholder={keywords.length === 0 ? "Type keyword & press Enter (e.g. webgl, react, seo)" : "Add tag..."}
                    className="flex-1 min-w-[140px] text-xs outline-none py-1 px-1"
                  />
                </div>
                <p className="text-[11px] text-gray-400 mt-1">
                  Press Enter or comma to insert tags. These will appear on the card and in SEO meta tags.
                </p>
              </div>

              {/* Content Markdown Area with Tab Switcher */}
              <div>
                <div className="flex items-center justify-between mb-1">
                  <div className="flex items-center gap-2">
                    <label className="block text-xs font-semibold text-gray-700 uppercase tracking-wider">
                      Article Body (Markdown) *
                    </label>
                    <span className="text-xs text-gray-500 font-mono">
                      {wordCount} words • ~{estimatedReadTime} min read
                    </span>
                  </div>

                  {/* Tabs: Write vs Preview */}
                  <div className="flex items-center rounded-md bg-gray-100 p-0.5 text-xs">
                    <button
                      type="button"
                      onClick={() => setActiveTab('write')}
                      className={`px-3 py-1 rounded font-medium transition-colors ${
                        activeTab === 'write' ? 'bg-white shadow-sm text-gray-900' : 'text-gray-600 hover:text-gray-900'
                      }`}
                    >
                      Markdown Editor
                    </button>
                    <button
                      type="button"
                      onClick={() => setActiveTab('preview')}
                      className={`px-3 py-1 rounded font-medium transition-colors ${
                        activeTab === 'preview' ? 'bg-white shadow-sm text-gray-900' : 'text-gray-600 hover:text-gray-900'
                      }`}
                    >
                      Live Preview
                    </button>
                  </div>
                </div>

                {activeTab === 'write' ? (
                  <div className="relative">
                    <textarea
                      required
                      rows={14}
                      value={content}
                      onChange={(e) => setContent(e.target.value)}
                      placeholder="# Heading 1&#10;&#10;Write your article body here in Markdown format...&#10;&#10;### Subheading&#10;&#10;- Bullet point 1&#10;- Bullet point 2&#10;&#10;**Bold text** and *italic text*."
                      className="w-full font-mono text-sm p-3 border border-gray-300 rounded-md focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 leading-relaxed"
                    />
                    <div className="text-[11px] text-gray-400 mt-1 flex items-center justify-between">
                      <span>Supports Headings (`#`, `##`), Lists (`-`, `1.`), Bold (`**`), Blockquotes (`&gt;`), Links (`[text](url)`).</span>
                      <span className="font-semibold text-gray-500">Pure text only (No images)</span>
                    </div>
                  </div>
                ) : (
                  <div className="border border-gray-300 rounded-md p-6 bg-gray-900 text-gray-100 min-h-[300px] max-h-[400px] overflow-y-auto">
                    <div className="prose prose-invert max-w-none text-left">
                      <Markdown components={{ img: () => null }}>
                        {content || '*No content to preview yet. Switch to Markdown Editor to write.*'}
                      </Markdown>
                    </div>
                  </div>
                )}
              </div>

              {/* Publication Settings */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-3 border-t border-gray-200">
                <div className="flex items-center gap-3">
                  <input
                    type="checkbox"
                    id="published-checkbox"
                    checked={published}
                    onChange={(e) => setPublished(e.target.checked)}
                    className="w-4 h-4 text-indigo-600 rounded border-gray-300 focus:ring-indigo-500 cursor-pointer"
                  />
                  <label htmlFor="published-checkbox" className="text-sm font-medium text-gray-800 cursor-pointer">
                    Publish immediately (Visible on live site)
                  </label>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-gray-700 uppercase tracking-wider mb-1">
                    Publish Timestamp
                  </label>
                  <input
                    type="datetime-local"
                    value={publishedAt}
                    onChange={(e) => setPublishedAt(e.target.value)}
                    className="w-full px-3 py-1.5 border border-gray-300 rounded-md text-xs font-mono"
                  />
                </div>
              </div>

              {/* Actions */}
              <div className="flex items-center justify-end gap-3 pt-4 border-t border-gray-200">
                <button
                  type="button"
                  onClick={() => setIsEditing(false)}
                  className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={saveStatus === 'saving'}
                  className="px-6 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-md text-sm font-medium transition-colors shadow-sm cursor-pointer disabled:opacity-50"
                >
                  {saveStatus === 'saving' ? 'Saving...' : editingId ? 'Save Changes' : 'Publish Article'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
